
networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/lmahe/data/mariadb'
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/lmahe/data/wordpress'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql/
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 6s
      timeout: 1s
      retries: 15
      start_period: 5s


  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html/
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: netstat -an | grep 9000 > /dev/null; if [ 0 != $$? ]; then exit 1; fi;
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s



  nginx:
    container_name: nginx
    image: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy
